image: atlassian/default-image:2
definitions:
  steps:
    - step: &build1
        name: Node Build
        image: node:8.9.4
        caches:
          - node
        script:
          - npm install
    - step: &deploy
        name: Deploy to Staging
        deployment: Staging
        script:
          - apt-get update
          - apt-get install -y zip
          - zip -r application1.zip .
          - pipe: atlassian/aws-code-deploy:0.5.3
            variables:
              AWS_DEFAULT_REGION: 'ap-southeast-2'
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: 'CodeDeployApp'
              S3_BUCKET: 'bitbucket-codedeploy-artifact-repository'
              COMMAND: 'upload'
              ZIP_FILE: 'application1.zip'
              VERSION_LABEL: yan.kiwi$(date +%Y-%m-%d)_$BITBUCKET_BUILD_NUMBER
              FOLDER: 'yan.bbtdevelopment'
          - pipe: atlassian/aws-code-deploy:0.5.3
            variables:
              AWS_DEFAULT_REGION: 'ap-southeast-2'
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: 'CodeDeployApp'
              DEPLOYMENT_GROUP: 'staging-deployment-group'
              S3_BUCKET: 'bitbucket-codedeploy-artifact-repository'
              COMMAND: 'deploy'
              WAIT: 'true'
              VERSION_LABEL: yan.kiwi$(date +%Y-%m-%d)_$BITBUCKET_BUILD_NUMBER
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
              FOLDER: 'yan.bbtdevelopment' 
        after-script:
          - ALERT_TYPE="Success"
          - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then ALERT_TYPE="Error" ; fi
          - pipe: atlassian/email-notify:0.3.12
            variables:
              USERNAME: 'abryan@bbtdigital.com'
              PASSWORD: $GMAIL_PASSWORD
              FROM: 'abryan@bbtdigital.com'
              TO: 'abryan@bbtdigital.com'
              HOST: 'smtp.gmail.com'
              SUBJECT: '${ALERT_TYPE}:Bitbucket Pipe Notification for ${BITBUCKET_BRANCH}'
pipelines:
  branches:
    feature/*:
      - step:
          image: openjdk:8 # This step uses its own image
          script:
            - echo "This script runs only on commit to branches with names that match the feature/* pattern."
    develop:
      - step: *build1
      - step: 
          <<: *deploy
          name: Deploy to Staging
          deployment: staging            
    master:
      - step: *build1
      - step:
          <<: *deploy
          name: Deploy to Prod
          deployment: production
          trigger: manual
          script:
            - apt-get update
            - apt-get install -y zip
            - zip -r application1.zip .
            - pipe: atlassian/aws-code-deploy:0.5.3
              variables:
                AWS_DEFAULT_REGION: 'ap-southeast-2'
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: 'CodeDeployApp'
                S3_BUCKET: 'bitbucket-codedeploy-artifact-repository'
                COMMAND: 'upload'
                ZIP_FILE: 'application1.zip'
                VERSION_LABEL: yan.kiwi$(date +%Y-%m-%d)_$BITBUCKET_BUILD_NUMBER
                FOLDER: 'yan.bbtdevelopment'
            - pipe: atlassian/aws-code-deploy:0.5.3
              variables:
                AWS_DEFAULT_REGION: 'ap-southeast-2'
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: 'CodeDeployApp'
                DEPLOYMENT_GROUP: 'production-deployment-group'
                S3_BUCKET: 'bitbucket-codedeploy-artifact-repository'
                COMMAND: 'deploy'
                WAIT: 'true'
                VERSION_LABEL: yan.kiwi$(date +%Y-%m-%d)_$BITBUCKET_BUILD_NUMBER
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
                FOLDER: 'yan.bbtdevelopment'
